spring:     
  datasource: #DB 접속
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: user01
    password: 1234
    hikari: #커넥션풀 
      connectionTimeout : 30000 #클라이언트가 pool에 connection을 요청하는데 기다리는 최대시간을 설정 30초
      maximumPoolSize : 10 #최대 커넥션 개수 설정
      maxLifetime : 1800000  #커넥션 풀에서 살아있을 수 있는 커넥션의 최대 수명시간 1,800초(30분)
      
  messages: #메시지
    basename: messages.validation
    encoding: UTF-8
    
  devtools: #View reload
    livereload:
      enabled: true
    
    restart: #컨트롤러, 모델단이 바뀌었을 때 프로젝트 재시작 설정 (정확히는 classpath에 있는 모든 파일)
      enabled: true #재시작 하지 않음

  thymeleaf:
    prefix: classpath:templates/views/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false #캐시를 사용하지 않음

mybatis: #mybatis 설정
  type-aliases-package: kr.spring.**.vo 
  mapper-locations: kr/spring/**/dao/*.xml
  
logging: #로그 지정
  level:
    '[kr.spring]': debug 
    
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    max-http-form-post-size: 200MB

  
    
    
 

  
  
  